<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXahJTxz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXahJTxz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXahJTxz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXahJTxz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXahJTxz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XahJTxz',
    'container.build_id' => '8d904c6f',
    'container.build_time' => 1616973454,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXahJTxz');
